### ISSUE TITLE
Switch your CoC to NCoC

### ISSUE THREAD

**Issue by Tataarujin** [Polyfrost/OneConfig#287]
What if you considered an alternative to the current Code of Conduct (CoC)? I'd like to introduce NCoC (No Code of Conduct), which promotes a straightforward and clear principle: behaving like a responsible adult. Unlike the current CoC with numerous detailed and confusing rules which gives you no wiggle room and treats people with a presumption of guilt, NCoC aims for simplicity. Take a look here: https://github.com/domgetter/NCoC 
Your thoughts on this idea are appreciated!

**Comment by Tataarujin** [comment]
> you shouldn't be contributing to our projects

I'm not here to contribute to this proj, pal, I'm here to barge in the project that I have nothing to do with, just like you (one of you) do. I'm here to propose changes nobody wants and to preach about things nobody needs, just like you (one of you) do. And I'm here to ask to establish a set of rules that will be forced with an iron hand and cold heart, like you folks love and do
.
If you wonder what I'm talking about, ask Pauline. This person did all of the above. This person barged in to the project that has no trace of that person's activity instead of one issue opened: to introduce extremely restrictive, minority-centered and, frankly, absolutely insane Contributor's CoC to it. And people in that repo did not lock it down like you just did, they actually tried to figure out, why they need it, what would it improve and how it will actually make project better.

Of course, you don't understand how this set of rules is restrictive. It's all about protecting YOU, the Minority, from THEM, the Majority. It's all about elevating you to the Holier-Than-Thou status without you doing anything of the merit to actually make it an achievement, simply based on the fact that you're the Minority. It's all about becoming digital patricians who will be protected by the rules that were designed not to equalize people, but to create noblemen among barbarians. Because rules that make people EQUAL are written out of RESPECT, unlike these rules in CCoC, which are written out of FEAR.

Have you read Harry Potter? There was a character, Dolores Umbridge, who dared to set new rules, as rectrictive and micromanaging as CCoC. She forced Potter to write "I should not lie" with his own blood. She was all cutesy outside but a monster inside. In the end, the wall with new rules has fallen, and she became a victim of her own rules. Read the book to know how.

I came here expecting you to close this issue after my first message and you did exactly as planned. I came to leave a final message of utmost desperation. You and your rules that control every interaction between human being... You are a menace. But, as all things in life, it will pass. Hopefully.

I have spoken.

**Comment by Wyvest** [comment]
> > you shouldn't be contributing to our projects
> 
> I'm not here to contribute to this proj, pal, I'm here to barge in the project that I have nothing to do with, just like you (one of you) do. I'm here to propose changes nobody wants and to preach about things nobody needs, just like you (one of you) do. And I'm here to ask to establish a set of rules that will be forced with an iron hand and cold heart, like you folks love and do . If you wonder what I'm talking about, ask Pauline. This person did all of the above. This person barged in to the project that has no trace of that person's activity instead of one issue opened: to introduce extremely restrictive, minority-centered and, frankly, absolutely insane Contributor's CoC to it. And people in that repo did not lock it down like you just did, they actually tried to figure out, why they need it, what would it improve and how it will actually make project better.
> 
> Of course, you don't understand how this set of rules is restrictive. It's all about protecting YOU, the Minority, from THEM, the Majority. It's all about elevating you to the Holier-Than-Thou status without you doing anything of the merit to actually make it an achievement, simply based on the fact that you're the Minority. It's all about becoming digital patricians who will be protected by the rules that were designed not to equalize people, but to create noblemen among barbarians. Because rules that make people EQUAL are written out of RESPECT, unlike these rules in CCoC, which are written out of FEAR.
> 
> Have you read Harry Potter? There was a character, Dolores Umbridge, who dared to set new rules, as rectrictive and micromanaging as CCoC. She forced Potter to write "I should not lie" with his own blood. She was all cutesy outside but a monster inside. In the end, the wall with new rules has fallen, and she became a victim of her own rules. Read the book to know how.
> 
> I came here expecting you to close this issue after my first message and you did exactly as planned. I came to leave a final message of utmost desperation. You and your rules that control every interaction between human being... You are a menace. But, as all things in life, it will pass. Hopefully.
> 
> I have spoken.

And I (or we, but mostly I) don't care either. If Pauline hadn't informed me of this around 1~2 day ago, I wouldn't have a clue about any of this. Our CoC is written not to put anyone on a pedestal (if you knew how to read, you would know this); this is somehow necessary because people, in 2023, don't understand what it means not to be racist, sexist, homophobic, transphobic, or anything phobic really. 

I closed the issue because the issue was solved and I like using GitHub properly (to an extent). This issue isn't locked, and I haven't blocked you from our organization or personally. Actually, I think our CoC is slightly redundant; we do most of our communications via Discord, where we have a separate list of rules (which are a lot easier to follow, as it was intended for younger people). Most of the time, communication between developers is done there as well. But I keep it there, because why the hell not? What’s wrong with not discriminating against minorities, or respecting others?

I'd also like to remind you of the scope of this project. This is a Minecraft modding library that allows developers to create convenient config UIs for the user. According to some blog posts I read, Hyprland is a Wayland compositor that has pretty cool animations and customization to it. This applies to both projects, but more so OneConfig - by stirring controversy into these spaces, you aren't doing anything at all. Do you think Joe Biden cares about or even uses Linux? Do you think he wants to conveniently configure his 1.8.9 Minecraft mods by using OneConfig? Even if he did, do you think he would be entering or contributing to the code or community of these, frankly, currently super niche projects? Obviously, no. You are not anyone's savior; you are not saving the world from the "wokeness" of society, or saving all the cisgender white males from destruction by the terrible minorities. Would a reasonable "adult" really bring out this conversation here? Would he really be striking up an argument with a 14-year-old? I thought two wrongs didn't make a right, no? This is just really petty and hypocritical, in my opinion.

(Also, there's a PR for a CoC in Hyprland now, so... https://github.com/hyprwm/Hyprland/pull/3366)

If you want to VC with me regarding this, let me know. I’d be more than happy to answer any questions you may have about our code or our CoC. Overall, considering you haven't contributed anything to Hyprland or OneConfig, I don't see why you were motivated to make this issue and make such a big fuss about it.

**Comment by Wyvest** [comment]
Also, I have just realized that linking the Hyprland PR in my previous post would also post this issue in that PR. I have nothing against Hyprland, I don't even use Linux in the first place. If it wasn't clear in the previous post, please don't bring anything relating to that drama over to OneConfig / Polyfrost, as that would be a waste of time for everyone.

**Comment by Zetvue** [comment]
> What if you considered an alternative to the current Code of Conduct (CoC)? I'd like to introduce NCoC (No Code of Conduct), which promotes a straightforward and clear principle: behaving like a responsible adult. Unlike the current CoC with numerous detailed and confusing rules which gives you no wiggle room and treats people with a presumption of guilt, NCoC aims for simplicity. Take a look here: https://github.com/domgetter/NCoC Your thoughts on this idea are appreciated!

I'm just gonna reply to this because why not?
I feel like the NCoC you suggest here is redundant, because the CoC here is essentially the same, just more specific: **  **

Now, I want to address a point, because I just feel this is a retarded statement:

> Of course, you don't understand how this set of rules is restrictive. It's all about protecting YOU, the Minority, from THEM, the Majority. It's all about elevating you to the Holier-Than-Thou status without you doing anything of the merit to actually make it an achievement, simply based on the fact that you're the Minority. It's all about becoming digital patricians who will be protected by the rules that were designed not to equalize people, but to create noblemen among barbarians. Because rules that make people EQUAL are written out of RESPECT, unlike these rules in CCoC, which are written out of FEAR.

**Where in this Code of Conduct does it say anything equivalent to** "`it's all about elevating you to the Holier-Than-Thou status without you doing anything of the merit to actually make it an achievement, simply based on the fact that you're the Minority`"**?** This is just guidelines on what to do and what not to do. I can't imagine that any of the unacceptable things the Conduct only apply to certain people. No -- it applies to everyone.

I do think the pledge is a bit excessive on including everyone (specifically "`We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.`" -- I think a simple everyone would work fine anyways), but, aside from that, there's nothing else stating that a pedestal would be formed simply for being a minority.

Note I don't really care much about the politics of other people, nor do I contribute to this project. I just wanted to respond just because.

**Comment by Tataarujin** [comment]
I will respond to this. First of all, since you judge people by their origin and disqualificate opinions written by white males - I'm not white in normal sense of the word, my skin is tanned, and English is not my first language. I'm "white-minded", if you can call it that. My origin is in Tajikistan, it's Central Asia. I will not tell the country where I live right now but it's not in the West.

I started this discussion because I want to express my opinion about the Internet in all, which is not the place of free speech anymore. I miss the days where people could just joke about everything and everyone which is now called "hate speech". It was the Wild West of discussions and opinions where everyone could joke about race, age and other "protected" traits without being called homophobe, sexist, agist or other -ist or -phobe. Good times. 

But today we have a really distopian place where strict (and often redundant and/or micromanaging to the absurd levels) rules are enforced with unseen zeal, enforcers are problematic people from the list of "protected" minorities on power trip. And these enforcers are allowing themselves to write the most disgusting things about people who do not share the same identity. I've seen that multiple times in Discord and in X. How is that harassment-free experience? How are they able to harass "normal" people but people are not allowed to fight back because they're "PLEDGED" (seriously, WTF?) to `make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation` crap. So, the only hope is to cope with pressure from the privileged few and hope for the best.

**Comment by MicrocontrollersDev** [comment]
I want to preface this by saying I am not directly affiliated here. I am not on the Polyfrost team and have only contributed to some projects.

Firstly, this response is cool and all but I cannot get over the fact that you called Twitter X.

Anyways, there’s a difference between a simple joke and taking things too far. I have not seen a simple joke cross over the line to harassment or rudeness on this repository nor community. The only close scenarios I’ve seen are from people who join the discord just to say something incredibly rude or controversial knowing they will be banned and that it was not a joke in the first place. Also, I don’t see how anything that happens in other Discord servers or on Twitter has any effect on this CoC.

Additionally, the line you state is crap for being unequal clearly states that it applies to all people regardless of [several things]. It does not only apply to, so called, “normal” people when talking about, what I can assume, “not normal” people. It goes both ways. And like I said earlier, there’s a line to be drawn between a joke and hate speech.

Again, feel free to be a part of this community, join the discord server, and see for yourself if the things you mention happening elsewhere happen in this community. If there’s an issue in this community it would be better to directly point that out instead of making snarky remarks and talking about other communities. So far, I’ve seen no evidence of power tripping here. The CoC is just a basis of set of standards to uphold and there’s absolutely nothing wrong with having one. If there is a specific line or lines that you feel are unfair then you should mention that instead and how it can be fixed. This conversation otherwise ultimately leads nowhere.

**Comment by Zetvue** [comment]
> I will respond to this. First of all, since you judge people by their origin and disqualificate opinions written by white males - I'm not white in normal sense of the word, my skin is tanned, and English is not my first language. I'm "white-minded", if you can call it that. My origin is in Tajikistan, it's Central Asia. I will not tell the country where I live right now but it's not in the West.

...that's racist? Why would people do this? Are you telling me I automatically think everyone (including you) is white?

> I started this discussion because I want to express my opinion about the Internet in all, which is not the place of free speech anymore. I miss the days where people could just joke about everything and everyone which is now called "hate speech". It was the Wild West of discussions and opinions where everyone could joke about race, age and other "protected" traits without being called homophobe, sexist, agist or other -ist or -phobe. Good times.

You can... still do that. Just not with some people.

> But today we have a really distopian place where strict (and often redundant and/or micromanaging to the absurd levels) rules are enforced with unseen zeal, enforcers are problematic people from the list of "protected" minorities on power trip. And these enforcers are allowing themselves to write the most disgusting things about people who do not share the same identity with them. I've seen that multiple times in Discord and in X. How is that harassment-free experience? How are they able to harass "normal" people but people are not allowed to fight back because they're "PLEDGED" (seriously, WTF?) to `make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation` crap. So, the only hope is to cope with pressure from the privileged few and hope for the best.

I do agree that putting people just for having a certain trait is stupid, but... that's not happening here, and this is unrelated to the CoC discussion in any manner. No "power-tripping" is happening here, and, if there is, I'd really like you to report it to the admins. I know them, they're reasonable. Especially Wyvest and Lynith, and... well, mostly Wyvest and Lynith.
Talking about "`And these enforcers are allowing themselves to write the most disgusting things about people who do not share the same identity with them. I've seen that multiple times in Discord and in X. How is that harassment-free experience?`", first, it's Twitter and not X. I'm just kidding, I don't care. Anyway, if you do see those comments... please report them to Discord or the admins. Telling someone awful shit is just horrible for everyone. And I'm being serious. It DOES NOT matter if you tell "kill yourself" to someone white, someone straight, someone cis, trans, black, etcetera. It's equally horrible.

> And make no mistake, I don't wish to harass people based solely on their identity, no matter how "protected" it is. I simply wish for equal opportunity for everyone in the community, to be able to put down people on power trip who are harassing other "unprotected" people left and right without being cancelled for being -ist or -phobe. Or to give everyone the right to joke about other's trait without being cancelled. In both cases, I wish for people to be equal.

Ok... that is what's happening here. We're all equal. 
Anyway, this reply didn't really address the main point, which is the CoC. If you have an issue with it, just state what you want fixed and we can discuss that.

**Comment by RoseGoldIsntGay** [comment]
what

**Comment by Zetvue** [comment]
> what
i'll be honest i wish iwere you right now
